- name: Install node JS
  hosts: web
  become: true

  tasks:
    # - name: Disable old nodejs and enable new nodejs
    #   ansible.builtin.shell: 
    #     cmd: dnf module disable nodejs -y && dnf module enable nodejs:18 -y

    # - name: Install NodeJS
    #   ansible.builtin.dnf:
    #     name: nodejs
    #     state: present

    - name: Create linux user
      ansible.builtin.user:
        name: catalogue

    - name: Create application directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download catalogue application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp/catalogue.zip
    
    - name: Unarchive the application
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes
    
    - name: Install the dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app
    
    - name: Copy catalogue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Load the service
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: true

    - name: Install mongodb mongosh
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: Restart and enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: true
