- name: Deploy catalogue service
  hosts: web
  become: true

  tasks:
    - name: Check if Node.js is installed
      ansible.builtin.command: node -v
      register: node_version
      ignore_errors: yes

    - name: Install Node.js 18 if missing
      ansible.builtin.shell: |
        curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
        dnf install -y nodejs
      when: node_version.rc != 0

    - name: Create linux user if not exists
      ansible.builtin.user:
        name: catalogue
        state: present

    - name: Create application directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download catalogue application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp/catalogue.zip

    - name: Unarchive the application
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install the dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: Copy catalogue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Load the service
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: true

    - name: Install mongodb mongosh
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: Restart and enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: true
